services:
  nexus:
    image: sonatype/nexus3:3.71.0
    container_name: nexus
    ports:
      - "8081:8081"
      - "8083:8083"
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-todo-api}:${IMAGE_TAG:-local}
    container_name: todo-api
    environment:
      PORT: 5000
      APP_VERSION: ${IMAGE_TAG:-local}
      DB_PATH: /app/data/tasks.db
    ports:
      - "5000:5000"
    volumes:
      - app_data:/app/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.3
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  nexus_data:
  app_data:
  prometheus_data:
  grafana_data:
