apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: devops-final
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.devops-final.svc.cluster.local:9090
        isDefault: true
        editable: true
